# Schema for Smalk module configuration.
smalk.settings:
  type: config_object
  label: 'Smalk settings'
  mapping:
    project_key:
      type: string
      label: 'Project Key'
    api_key:
      type: string
      label: 'API Key'
    enabled:
      type: boolean
      label: 'Enable module'
    tracking_enabled:
      type: boolean
      label: 'Enable tracking (JS + server-side)'
    ads_enabled:
      type: boolean
      label: 'Enable ad injection'
    api_timeout:
      type: float
      label: 'API Timeout (seconds)'
    exclude_admin_pages:
      type: boolean
      label: 'Exclude admin pages'
    excluded_paths:
      type: string
      label: 'Excluded paths'
    debug_mode:
      type: boolean
      label: 'Debug mode'
